package inheritance;

public class Dog extends Animal {

	private String earShape;
	private String tailShape;
	
	public Dog() {
		super("mutt","big",50);
	}

	public Dog(String type, double weight) {
		this(type,weight,"Perky","Curly");	
	}
	public Dog(String type,  double weight, String earShape, String tailShape) {
		super(type,  weight <15? "Small":(weight<35?"medium":"large"), weight);
		this.earShape = earShape;
		this.tailShape = tailShape;
	}
	
	// on left we can see the arrow which tell its parent class overriden method
	public void makeNoise() {
		// on animal class if type is private , subclass does not allow to access
		if(type=="wolf") {
			System.out.println("ow woo");
		}
		bark();
	}
	
	
	// this method is generated by using ide
	@Override
	public void move(String speed) {
		// TODO Auto-generated method stub
		super.move(speed);
	//	System.out.println("dog walk , run and wag their tails");
		if(speed=="slow") {
			walk();
			wagTail();
			
		}else
		{
			run();
			bark();
		}
		System.out.println();
	}
	
	// create below 4 method specific to the dog class
	private void bark() {
		System.out.print(" woof !");
	}
	
	private void run() {
		System.out.print(" dog running ");
	}

	private void walk() {
		System.out.print(" dog walking");
	}
	private void wagTail() {
		System.out.print(" Tail wagging");
	}
	
	@Override
	// to generate super.tostring , select the checkbox inhertance to string as well
	public String toString() {
		return "Dog [earShape=" + earShape + ", tailShape=" + tailShape + ", toString()=" + super.toString() + "]";
	}
	
	
}
